version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_16_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myapp"]
      interval: 5s
      timeout: 5s
      retries: 10

  cpp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp_application
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    restart: on-failure

volumes:
  postgres_16_data:

networks:
  app-network:
    driver: bridge