// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef ACCESS_PERMISSION_ODB_HPP
#define ACCESS_PERMISSION_ODB_HPP

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "access_permission.hpp"

#include "user_role-odb.hpp"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // AccessPermission
  //
  template <>
  struct class_traits< ::models::AccessPermission >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::models::AccessPermission >
  {
    public:
    typedef ::models::AccessPermission object_type;
    typedef ::models::AccessPermission* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // RolePermission
  //
  template <>
  struct class_traits< ::models::RolePermission >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::models::RolePermission >
  {
    public:
    typedef ::models::RolePermission object_type;
    typedef ::models::RolePermission* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // AccessPermission
  //
  template <typename A>
  struct query_columns< ::models::AccessPermission, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    id_type_;

    static const id_type_ id;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;

    // description
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    description_type_;

    static const description_type_ description;
  };

  template <typename A>
  const typename query_columns< ::models::AccessPermission, id_pgsql, A >::id_type_
  query_columns< ::models::AccessPermission, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::models::AccessPermission, id_pgsql, A >::name_type_
  query_columns< ::models::AccessPermission, id_pgsql, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::models::AccessPermission, id_pgsql, A >::description_type_
  query_columns< ::models::AccessPermission, id_pgsql, A >::
  description (A::table_name, "\"description\"", 0);

  template <typename A>
  struct pointer_query_columns< ::models::AccessPermission, id_pgsql, A >:
    query_columns< ::models::AccessPermission, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::models::AccessPermission, id_pgsql >:
    public access::object_traits< ::models::AccessPermission >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      // name_
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // description_
      //
      details::buffer description_value;
      std::size_t description_size;
      bool description_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 3UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::models::AccessPermission, id_common >:
    public access::object_traits_impl< ::models::AccessPermission, id_pgsql >
  {
  };

  // RolePermission
  //
  template <typename A>
  struct pointer_query_columns< ::models::RolePermission, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // role
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    role_type_;

    static const role_type_ role;

    // permission
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    permission_type_;

    static const permission_type_ permission;

    // granted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    granted_at_type_;

    static const granted_at_type_ granted_at;
  };

  template <typename A>
  const typename pointer_query_columns< ::models::RolePermission, id_pgsql, A >::id_type_
  pointer_query_columns< ::models::RolePermission, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::models::RolePermission, id_pgsql, A >::role_type_
  pointer_query_columns< ::models::RolePermission, id_pgsql, A >::
  role (A::table_name, "\"role_id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::models::RolePermission, id_pgsql, A >::permission_type_
  pointer_query_columns< ::models::RolePermission, id_pgsql, A >::
  permission (A::table_name, "\"permission_id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::models::RolePermission, id_pgsql, A >::granted_at_type_
  pointer_query_columns< ::models::RolePermission, id_pgsql, A >::
  granted_at (A::table_name, "\"granted_at\"", 0);

  template <>
  class access::object_traits_impl< ::models::RolePermission, id_pgsql >:
    public access::object_traits< ::models::RolePermission >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // role_
      //
      details::buffer role_value;
      std::size_t role_size;
      bool role_null;

      // permission_
      //
      details::buffer permission_value;
      std::size_t permission_size;
      bool permission_null;

      // granted_at_
      //
      long long granted_at_value;
      bool granted_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct role_tag;
    struct permission_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::models::RolePermission, id_common >:
    public access::object_traits_impl< ::models::RolePermission, id_pgsql >
  {
  };

  // AccessPermission
  //
  // RolePermission
  //
  template <>
  struct alias_traits<
    ::models::UserRole,
    id_pgsql,
    access::object_traits_impl< ::models::RolePermission, id_pgsql >::role_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::models::AccessPermission,
    id_pgsql,
    access::object_traits_impl< ::models::RolePermission, id_pgsql >::permission_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::models::RolePermission, id_pgsql >
  {
    // role
    //
    typedef
    odb::alias_traits<
      ::models::UserRole,
      id_pgsql,
      access::object_traits_impl< ::models::RolePermission, id_pgsql >::role_tag>
    role_alias_;

    // permission
    //
    typedef
    odb::alias_traits<
      ::models::AccessPermission,
      id_pgsql,
      access::object_traits_impl< ::models::RolePermission, id_pgsql >::permission_tag>
    permission_alias_;
  };

  template <typename A>
  struct query_columns< ::models::RolePermission, id_pgsql, A >:
    query_columns_base< ::models::RolePermission, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        long unsigned int,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // role
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    role_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::models::UserRole,
        id_pgsql,
        role_alias_ > >
    role_pointer_type_;

    struct role_type_: role_pointer_type_, role_column_type_
    {
      role_type_ (const char* t, const char* c, const char* conv)
        : role_column_type_ (t, c, conv)
      {
      }
    };

    static const role_type_ role;

    // permission
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    permission_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::models::AccessPermission,
        id_pgsql,
        permission_alias_ > >
    permission_pointer_type_;

    struct permission_type_: permission_pointer_type_, permission_column_type_
    {
      permission_type_ (const char* t, const char* c, const char* conv)
        : permission_column_type_ (t, c, conv)
      {
      }
    };

    static const permission_type_ permission;

    // granted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    granted_at_type_;

    static const granted_at_type_ granted_at;
  };

  template <typename A>
  const typename query_columns< ::models::RolePermission, id_pgsql, A >::id_type_
  query_columns< ::models::RolePermission, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::models::RolePermission, id_pgsql, A >::role_type_
  query_columns< ::models::RolePermission, id_pgsql, A >::
  role (A::table_name, "\"role_id\"", 0);

  template <typename A>
  const typename query_columns< ::models::RolePermission, id_pgsql, A >::permission_type_
  query_columns< ::models::RolePermission, id_pgsql, A >::
  permission (A::table_name, "\"permission_id\"", 0);

  template <typename A>
  const typename query_columns< ::models::RolePermission, id_pgsql, A >::granted_at_type_
  query_columns< ::models::RolePermission, id_pgsql, A >::
  granted_at (A::table_name, "\"granted_at\"", 0);
}

#include "access_permission-odb.ipp"

#include <odb/post.hxx>

#endif // ACCESS_PERMISSION_ODB_HPP
