/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "role_permission" CASCADE;

DROP TABLE IF EXISTS "access_permission" CASCADE;

CREATE TABLE "access_permission" (
  "id" VARCHAR(36) NOT NULL PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL,
  "description" TEXT NOT NULL);

CREATE UNIQUE INDEX "access_permission_name_i"
  ON "access_permission" ("name");

CREATE TABLE "role_permission" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "role_id" VARCHAR(36) NOT NULL,
  "permission_id" VARCHAR(36) NOT NULL,
  "granted_at" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  CONSTRAINT "permission_id_fk"
    FOREIGN KEY ("permission_id")
    REFERENCES "access_permission" ("id")
    INITIALLY DEFERRED);

ALTER TABLE "role_permission"
  ADD CONSTRAINT "role_id_fk"
    FOREIGN KEY ("role_id")
    REFERENCES "user_role" ("id")
    INITIALLY DEFERRED;

