// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "system_log-odb.hpp"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // SystemLog
  //

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  persist_statement_name[] = "persist_models_SystemLog";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  find_statement_name[] = "find_models_SystemLog";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  update_statement_name[] = "update_models_SystemLog";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  erase_statement_name[] = "erase_models_SystemLog";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  query_statement_name[] = "query_models_SystemLog";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  erase_query_statement_name[] = "erase_query_models_SystemLog";

  const unsigned int access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::int4_oid,
    pgsql::int4_oid,
    pgsql::text_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid
  };

  struct access::object_traits_impl< ::models::SystemLog, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::models::SystemLog, id_pgsql >::id_type
  access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        id,
        i.id_value,
        i.id_size,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    if (t[0UL])
    {
      i.id_value.capacity (i.id_size);
      grew = true;
    }

    // level_
    //
    t[1UL] = 0;

    // action_type_
    //
    t[2UL] = 0;

    // message_
    //
    if (t[3UL])
    {
      i.message_value.capacity (i.message_size);
      grew = true;
    }

    // timestamp_
    //
    t[4UL] = 0;

    // actor_
    //
    if (t[5UL])
    {
      i.actor_value.capacity (i.actor_size);
      grew = true;
    }

    // subject_
    //
    if (t[6UL])
    {
      i.subject_value.capacity (i.subject_size);
      grew = true;
    }

    // ip_address_
    //
    if (t[7UL])
    {
      i.ip_address_value.capacity (i.ip_address_size);
      grew = true;
    }

    // user_agent_
    //
    if (t[8UL])
    {
      i.user_agent_value.capacity (i.user_agent_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].type = pgsql::bind::text;
      b[n].buffer = i.id_value.data_ptr ();
      b[n].capacity = i.id_value.capacity ();
      b[n].size = &i.id_size;
      b[n].is_null = &i.id_null;
      n++;
    }

    // level_
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.level_value;
    b[n].is_null = &i.level_null;
    n++;

    // action_type_
    //
    b[n].type = pgsql::bind::integer;
    b[n].buffer = &i.action_type_value;
    b[n].is_null = &i.action_type_null;
    n++;

    // message_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.message_value.data_ptr ();
    b[n].capacity = i.message_value.capacity ();
    b[n].size = &i.message_size;
    b[n].is_null = &i.message_null;
    n++;

    // timestamp_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.timestamp_value;
    b[n].is_null = &i.timestamp_null;
    n++;

    // actor_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.actor_value.data_ptr ();
    b[n].capacity = i.actor_value.capacity ();
    b[n].size = &i.actor_size;
    b[n].is_null = &i.actor_null;
    n++;

    // subject_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.subject_value.data_ptr ();
    b[n].capacity = i.subject_value.capacity ();
    b[n].size = &i.subject_size;
    b[n].is_null = &i.subject_null;
    n++;

    // ip_address_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.ip_address_value.data_ptr ();
    b[n].capacity = i.ip_address_value.capacity ();
    b[n].size = &i.ip_address_size;
    b[n].is_null = &i.ip_address_null;
    n++;

    // user_agent_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.user_agent_value.data_ptr ();
    b[n].capacity = i.user_agent_value.capacity ();
    b[n].size = &i.user_agent_size;
    b[n].is_null = &i.user_agent_null;
    n++;
  }

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.id_value.data_ptr ();
    b[n].capacity = i.id_value.capacity ();
    b[n].size = &i.id_size;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      ::std::string const& v =
        o.id_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        v);
      i.id_null = is_null;
      i.id_size = size;
      grew = grew || (cap != i.id_value.capacity ());
    }

    // level_
    //
    {
      ::models::LogLevel const& v =
        o.level_;

      bool is_null (false);
      pgsql::value_traits<
          ::models::LogLevel,
          pgsql::id_integer >::set_image (
        i.level_value, is_null, v);
      i.level_null = is_null;
    }

    // action_type_
    //
    {
      ::models::ActionType const& v =
        o.action_type_;

      bool is_null (false);
      pgsql::value_traits<
          ::models::ActionType,
          pgsql::id_integer >::set_image (
        i.action_type_value, is_null, v);
      i.action_type_null = is_null;
    }

    // message_
    //
    {
      ::std::string const& v =
        o.message_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.message_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.message_value,
        size,
        is_null,
        v);
      i.message_null = is_null;
      i.message_size = size;
      grew = grew || (cap != i.message_value.capacity ());
    }

    // timestamp_
    //
    {
      ::std::string const& v =
        o.timestamp_;

      bool is_null (false);
      pgsql::value_traits<
          ::std::string,
          pgsql::id_timestamp >::set_image (
        i.timestamp_value, is_null, v);
      i.timestamp_null = is_null;
    }

    // actor_
    //
    {
      ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > > const& v =
        o.actor_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.actor_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > >,
          pgsql::id_string >::set_image (
        i.actor_value,
        size,
        is_null,
        v);
      i.actor_null = is_null;
      i.actor_size = size;
      grew = grew || (cap != i.actor_value.capacity ());
    }

    // subject_
    //
    {
      ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > > const& v =
        o.subject_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.subject_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > >,
          pgsql::id_string >::set_image (
        i.subject_value,
        size,
        is_null,
        v);
      i.subject_null = is_null;
      i.subject_size = size;
      grew = grew || (cap != i.subject_value.capacity ());
    }

    // ip_address_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.ip_address_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.ip_address_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_image (
        i.ip_address_value,
        size,
        is_null,
        v);
      i.ip_address_null = is_null;
      i.ip_address_size = size;
      grew = grew || (cap != i.ip_address_value.capacity ());
    }

    // user_agent_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.user_agent_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.user_agent_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_image (
        i.user_agent_value,
        size,
        is_null,
        v);
      i.user_agent_null = is_null;
      i.user_agent_size = size;
      grew = grew || (cap != i.user_agent_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      ::std::string& v =
        o.id_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.id_value,
        i.id_size,
        i.id_null);
    }

    // level_
    //
    {
      ::models::LogLevel& v =
        o.level_;

      pgsql::value_traits<
          ::models::LogLevel,
          pgsql::id_integer >::set_value (
        v,
        i.level_value,
        i.level_null);
    }

    // action_type_
    //
    {
      ::models::ActionType& v =
        o.action_type_;

      pgsql::value_traits<
          ::models::ActionType,
          pgsql::id_integer >::set_value (
        v,
        i.action_type_value,
        i.action_type_null);
    }

    // message_
    //
    {
      ::std::string& v =
        o.message_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.message_value,
        i.message_size,
        i.message_null);
    }

    // timestamp_
    //
    {
      ::std::string& v =
        o.timestamp_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_timestamp >::set_value (
        v,
        i.timestamp_value,
        i.timestamp_null);
    }

    // actor_
    //
    {
      ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > >& v =
        o.actor_;

      pgsql::value_traits<
          ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > >,
          pgsql::id_string >::set_value (
        v,
        i.actor_value,
        i.actor_size,
        i.actor_null);
    }

    // subject_
    //
    {
      ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > >& v =
        o.subject_;

      pgsql::value_traits<
          ::odb::nullable< ::odb::lazy_shared_ptr< ::models::User > >,
          pgsql::id_string >::set_value (
        v,
        i.subject_value,
        i.subject_size,
        i.subject_null);
    }

    // ip_address_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.ip_address_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_value (
        v,
        i.ip_address_value,
        i.ip_address_size,
        i.ip_address_null);
    }

    // user_agent_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.user_agent_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_value (
        v,
        i.user_agent_value,
        i.user_agent_size,
        i.user_agent_null);
    }
  }

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        id);
      i.id_null = is_null;
      i.id_size = size;
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::persist_statement[] =
  "INSERT INTO \"system_log\" "
  "(\"id\", "
  "\"level\", "
  "\"action_type\", "
  "\"message\", "
  "\"timestamp\", "
  "\"actor_id\", "
  "\"subject_id\", "
  "\"ip_address\", "
  "\"user_agent\") "
  "VALUES "
  "($1, $2, $3, $4, $5, $6, $7, $8, $9)";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::find_statement[] =
  "SELECT "
  "\"system_log\".\"id\", "
  "\"system_log\".\"level\", "
  "\"system_log\".\"action_type\", "
  "\"system_log\".\"message\", "
  "\"system_log\".\"timestamp\", "
  "\"system_log\".\"actor_id\", "
  "\"system_log\".\"subject_id\", "
  "\"system_log\".\"ip_address\", "
  "\"system_log\".\"user_agent\" "
  "FROM \"system_log\" "
  "WHERE \"system_log\".\"id\"=$1";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::update_statement[] =
  "UPDATE \"system_log\" "
  "SET "
  "\"level\"=$1, "
  "\"action_type\"=$2, "
  "\"message\"=$3, "
  "\"timestamp\"=$4, "
  "\"actor_id\"=$5, "
  "\"subject_id\"=$6, "
  "\"ip_address\"=$7, "
  "\"user_agent\"=$8 "
  "WHERE \"id\"=$9";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::erase_statement[] =
  "DELETE FROM \"system_log\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::query_statement[] =
  "SELECT "
  "\"system_log\".\"id\", "
  "\"system_log\".\"level\", "
  "\"system_log\".\"action_type\", "
  "\"system_log\".\"message\", "
  "\"system_log\".\"timestamp\", "
  "\"system_log\".\"actor_id\", "
  "\"system_log\".\"subject_id\", "
  "\"system_log\".\"ip_address\", "
  "\"system_log\".\"user_agent\" "
  "FROM \"system_log\"";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"system_log\"";

  const char access::object_traits_impl< ::models::SystemLog, id_pgsql >::table_name[] =
  "\"system_log\"";

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::models::SystemLog, id_pgsql >::pointer_type
  access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::models::SystemLog, id_pgsql >::object_type >
  access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::models::SystemLog, id_pgsql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
