/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "system_log" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "system_log" (
  "id" VARCHAR(36) NOT NULL PRIMARY KEY,
  "level" INTEGER NOT NULL,
  "action_type" INTEGER NOT NULL,
  "message" TEXT NOT NULL,
  "timestamp" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  "actor_id" VARCHAR(36) NULL,
  "subject_id" VARCHAR(36) NULL,
  "ip_address" VARCHAR(45) NULL,
  "user_agent" TEXT NULL);

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

