// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef USER_ODB_HPP
#define USER_ODB_HPP

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "user.hpp"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // User
  //
  template <>
  struct class_traits< ::models::User >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::models::User >
  {
    public:
    typedef ::models::User object_type;
    typedef ::models::User* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::std::string id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // User
  //
  template <typename A>
  struct query_columns< ::models::User, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    id_type_;

    static const id_type_ id;

    // first_name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    first_name_type_;

    static const first_name_type_ first_name;

    // last_name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    last_name_type_;

    static const last_name_type_ last_name;

    // patronymic
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    patronymic_type_;

    static const patronymic_type_ patronymic;

    // email
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    email_type_;

    static const email_type_ email;

    // phone
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    phone_type_;

    static const phone_type_ phone;

    // password_hash
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    password_hash_type_;

    static const password_hash_type_ password_hash;

    // is_active
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    is_active_type_;

    static const is_active_type_ is_active;

    // password_change_required
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    password_change_required_type_;

    static const password_change_required_type_ password_change_required;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // last_login_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    last_login_at_type_;

    static const last_login_at_type_ last_login_at;
  };

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::id_type_
  query_columns< ::models::User, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::first_name_type_
  query_columns< ::models::User, id_pgsql, A >::
  first_name (A::table_name, "\"first_name\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::last_name_type_
  query_columns< ::models::User, id_pgsql, A >::
  last_name (A::table_name, "\"last_name\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::patronymic_type_
  query_columns< ::models::User, id_pgsql, A >::
  patronymic (A::table_name, "\"patronymic\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::email_type_
  query_columns< ::models::User, id_pgsql, A >::
  email (A::table_name, "\"email\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::phone_type_
  query_columns< ::models::User, id_pgsql, A >::
  phone (A::table_name, "\"phone\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::password_hash_type_
  query_columns< ::models::User, id_pgsql, A >::
  password_hash (A::table_name, "\"password_hash\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::is_active_type_
  query_columns< ::models::User, id_pgsql, A >::
  is_active (A::table_name, "\"is_active\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::password_change_required_type_
  query_columns< ::models::User, id_pgsql, A >::
  password_change_required (A::table_name, "\"password_change_required\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::created_at_type_
  query_columns< ::models::User, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::updated_at_type_
  query_columns< ::models::User, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  const typename query_columns< ::models::User, id_pgsql, A >::last_login_at_type_
  query_columns< ::models::User, id_pgsql, A >::
  last_login_at (A::table_name, "\"last_login_at\"", 0);

  template <typename A>
  struct pointer_query_columns< ::models::User, id_pgsql, A >:
    query_columns< ::models::User, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::models::User, id_pgsql >:
    public access::object_traits< ::models::User >
  {
    public:
    struct id_image_type
    {
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      details::buffer id_value;
      std::size_t id_size;
      bool id_null;

      // first_name_
      //
      details::buffer first_name_value;
      std::size_t first_name_size;
      bool first_name_null;

      // last_name_
      //
      details::buffer last_name_value;
      std::size_t last_name_size;
      bool last_name_null;

      // patronymic_
      //
      details::buffer patronymic_value;
      std::size_t patronymic_size;
      bool patronymic_null;

      // email_
      //
      details::buffer email_value;
      std::size_t email_size;
      bool email_null;

      // phone_
      //
      details::buffer phone_value;
      std::size_t phone_size;
      bool phone_null;

      // password_hash_
      //
      details::buffer password_hash_value;
      std::size_t password_hash_size;
      bool password_hash_null;

      // is_active_
      //
      bool is_active_value;
      bool is_active_null;

      // password_change_required_
      //
      bool password_change_required_value;
      bool password_change_required_null;

      // created_at_
      //
      long long created_at_value;
      bool created_at_null;

      // updated_at_
      //
      long long updated_at_value;
      bool updated_at_null;

      // last_login_at_
      //
      long long last_login_at_value;
      bool last_login_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 12UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    static const std::size_t batch = 1UL;

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::models::User, id_common >:
    public access::object_traits_impl< ::models::User, id_pgsql >
  {
  };

  // User
  //
}

#include "user-odb.ipp"

#include <odb/post.hxx>

#endif // USER_ODB_HPP
