/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "app_user" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "app_user" (
  "id" VARCHAR(36) NOT NULL PRIMARY KEY,
  "first_name" VARCHAR(100) NOT NULL,
  "last_name" VARCHAR(100) NOT NULL,
  "patronymic" VARCHAR(100) NULL,
  "email" VARCHAR(255) NOT NULL,
  "phone" VARCHAR(20) NULL,
  "password_hash" VARCHAR(255) NOT NULL,
  "is_active" BOOLEAN NOT NULL,
  "password_change_required" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  "updated_at" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  "last_login_at" TIMESTAMP NULL);

CREATE UNIQUE INDEX "app_user_email_i"
  ON "app_user" ("email");

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

