/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user_role_assignment" CASCADE;

DROP TABLE IF EXISTS "schema_version";

CREATE TABLE "user_role_assignment" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "user_id" VARCHAR(36) NOT NULL,
  "role_id" VARCHAR(36) NOT NULL,
  "assigned_at" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP');

ALTER TABLE "user_role_assignment"
  ADD CONSTRAINT "user_id_fk"
    FOREIGN KEY ("user_id")
    REFERENCES "app_user" ("id")
    INITIALLY DEFERRED,
  ADD CONSTRAINT "role_id_fk"
    FOREIGN KEY ("role_id")
    REFERENCES "user_role" ("id")
    INITIALLY DEFERRED;

CREATE TABLE "schema_version" (
  "name" TEXT NOT NULL PRIMARY KEY,
  "version" BIGINT NOT NULL,
  "migration" BOOLEAN NOT NULL);

INSERT INTO "schema_version" (
  "name", "version", "migration")
  VALUES ('', 1, FALSE);

