/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS "user_role" CASCADE;

CREATE TABLE "user_role" (
  "id" VARCHAR(36) NOT NULL PRIMARY KEY,
  "name" VARCHAR(50) NOT NULL,
  "description" TEXT NOT NULL,
  "is_system" BOOLEAN NOT NULL,
  "created_at" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP',
  "updated_at" TIMESTAMP NOT NULL DEFAULT 'CURRENT_TIMESTAMP');

CREATE UNIQUE INDEX "user_role_name_i"
  ON "user_role" ("name");

