// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "user-odb.hpp"

#include <cassert>
#include <cstring>  // std::memcpy


#include <odb/pgsql/traits.hxx>
#include <odb/pgsql/database.hxx>
#include <odb/pgsql/transaction.hxx>
#include <odb/pgsql/connection.hxx>
#include <odb/pgsql/statement.hxx>
#include <odb/pgsql/statement-cache.hxx>
#include <odb/pgsql/simple-object-statements.hxx>
#include <odb/pgsql/container-statements.hxx>
#include <odb/pgsql/exceptions.hxx>
#include <odb/pgsql/simple-object-result.hxx>

namespace odb
{
  // User
  //

  const char access::object_traits_impl< ::models::User, id_pgsql >::
  persist_statement_name[] = "persist_models_User";

  const char access::object_traits_impl< ::models::User, id_pgsql >::
  find_statement_name[] = "find_models_User";

  const char access::object_traits_impl< ::models::User, id_pgsql >::
  update_statement_name[] = "update_models_User";

  const char access::object_traits_impl< ::models::User, id_pgsql >::
  erase_statement_name[] = "erase_models_User";

  const char access::object_traits_impl< ::models::User, id_pgsql >::
  query_statement_name[] = "query_models_User";

  const char access::object_traits_impl< ::models::User, id_pgsql >::
  erase_query_statement_name[] = "erase_query_models_User";

  const unsigned int access::object_traits_impl< ::models::User, id_pgsql >::
  persist_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid
  };

  const unsigned int access::object_traits_impl< ::models::User, id_pgsql >::
  find_statement_types[] =
  {
    pgsql::text_oid
  };

  const unsigned int access::object_traits_impl< ::models::User, id_pgsql >::
  update_statement_types[] =
  {
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::text_oid,
    pgsql::bool_oid,
    pgsql::bool_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::timestamp_oid,
    pgsql::text_oid
  };

  struct access::object_traits_impl< ::models::User, id_pgsql >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      pgsql::connection&,
      image_type&,
      id_image_type&,
      pgsql::binding&,
      pgsql::binding&,
      pgsql::native_binding&,
      const unsigned int*)
    {
    }
  };

  access::object_traits_impl< ::models::User, id_pgsql >::id_type
  access::object_traits_impl< ::models::User, id_pgsql >::
  id (const image_type& i)
  {
    pgsql::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        id,
        i.id_value,
        i.id_size,
        i.id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::models::User, id_pgsql >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // id_
    //
    if (t[0UL])
    {
      i.id_value.capacity (i.id_size);
      grew = true;
    }

    // first_name_
    //
    if (t[1UL])
    {
      i.first_name_value.capacity (i.first_name_size);
      grew = true;
    }

    // last_name_
    //
    if (t[2UL])
    {
      i.last_name_value.capacity (i.last_name_size);
      grew = true;
    }

    // patronymic_
    //
    if (t[3UL])
    {
      i.patronymic_value.capacity (i.patronymic_size);
      grew = true;
    }

    // email_
    //
    if (t[4UL])
    {
      i.email_value.capacity (i.email_size);
      grew = true;
    }

    // phone_
    //
    if (t[5UL])
    {
      i.phone_value.capacity (i.phone_size);
      grew = true;
    }

    // password_hash_
    //
    if (t[6UL])
    {
      i.password_hash_value.capacity (i.password_hash_size);
      grew = true;
    }

    // is_active_
    //
    t[7UL] = 0;

    // password_change_required_
    //
    t[8UL] = 0;

    // created_at_
    //
    t[9UL] = 0;

    // updated_at_
    //
    t[10UL] = 0;

    // last_login_at_
    //
    t[11UL] = 0;

    return grew;
  }

  void access::object_traits_impl< ::models::User, id_pgsql >::
  bind (pgsql::bind* b,
        image_type& i,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    std::size_t n (0);

    // id_
    //
    if (sk != statement_update)
    {
      b[n].type = pgsql::bind::text;
      b[n].buffer = i.id_value.data_ptr ();
      b[n].capacity = i.id_value.capacity ();
      b[n].size = &i.id_size;
      b[n].is_null = &i.id_null;
      n++;
    }

    // first_name_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.first_name_value.data_ptr ();
    b[n].capacity = i.first_name_value.capacity ();
    b[n].size = &i.first_name_size;
    b[n].is_null = &i.first_name_null;
    n++;

    // last_name_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.last_name_value.data_ptr ();
    b[n].capacity = i.last_name_value.capacity ();
    b[n].size = &i.last_name_size;
    b[n].is_null = &i.last_name_null;
    n++;

    // patronymic_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.patronymic_value.data_ptr ();
    b[n].capacity = i.patronymic_value.capacity ();
    b[n].size = &i.patronymic_size;
    b[n].is_null = &i.patronymic_null;
    n++;

    // email_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.email_value.data_ptr ();
    b[n].capacity = i.email_value.capacity ();
    b[n].size = &i.email_size;
    b[n].is_null = &i.email_null;
    n++;

    // phone_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.phone_value.data_ptr ();
    b[n].capacity = i.phone_value.capacity ();
    b[n].size = &i.phone_size;
    b[n].is_null = &i.phone_null;
    n++;

    // password_hash_
    //
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.password_hash_value.data_ptr ();
    b[n].capacity = i.password_hash_value.capacity ();
    b[n].size = &i.password_hash_size;
    b[n].is_null = &i.password_hash_null;
    n++;

    // is_active_
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.is_active_value;
    b[n].is_null = &i.is_active_null;
    n++;

    // password_change_required_
    //
    b[n].type = pgsql::bind::boolean_;
    b[n].buffer = &i.password_change_required_value;
    b[n].is_null = &i.password_change_required_null;
    n++;

    // created_at_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.created_at_value;
    b[n].is_null = &i.created_at_null;
    n++;

    // updated_at_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.updated_at_value;
    b[n].is_null = &i.updated_at_null;
    n++;

    // last_login_at_
    //
    b[n].type = pgsql::bind::timestamp;
    b[n].buffer = &i.last_login_at_value;
    b[n].is_null = &i.last_login_at_null;
    n++;
  }

  void access::object_traits_impl< ::models::User, id_pgsql >::
  bind (pgsql::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = pgsql::bind::text;
    b[n].buffer = i.id_value.data_ptr ();
    b[n].capacity = i.id_value.capacity ();
    b[n].size = &i.id_size;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::models::User, id_pgsql >::
  init (image_type& i,
        const object_type& o,
        pgsql::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace pgsql;

    bool grew (false);

    // id_
    //
    if (sk == statement_insert)
    {
      ::std::string const& v =
        o.id_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        v);
      i.id_null = is_null;
      i.id_size = size;
      grew = grew || (cap != i.id_value.capacity ());
    }

    // first_name_
    //
    {
      ::std::string const& v =
        o.first_name_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.first_name_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.first_name_value,
        size,
        is_null,
        v);
      i.first_name_null = is_null;
      i.first_name_size = size;
      grew = grew || (cap != i.first_name_value.capacity ());
    }

    // last_name_
    //
    {
      ::std::string const& v =
        o.last_name_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.last_name_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.last_name_value,
        size,
        is_null,
        v);
      i.last_name_null = is_null;
      i.last_name_size = size;
      grew = grew || (cap != i.last_name_value.capacity ());
    }

    // patronymic_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.patronymic_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.patronymic_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_image (
        i.patronymic_value,
        size,
        is_null,
        v);
      i.patronymic_null = is_null;
      i.patronymic_size = size;
      grew = grew || (cap != i.patronymic_value.capacity ());
    }

    // email_
    //
    {
      ::std::string const& v =
        o.email_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.email_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.email_value,
        size,
        is_null,
        v);
      i.email_null = is_null;
      i.email_size = size;
      grew = grew || (cap != i.email_value.capacity ());
    }

    // phone_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.phone_;

      bool is_null (true);
      std::size_t size (0);
      std::size_t cap (i.phone_value.capacity ());
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_image (
        i.phone_value,
        size,
        is_null,
        v);
      i.phone_null = is_null;
      i.phone_size = size;
      grew = grew || (cap != i.phone_value.capacity ());
    }

    // password_hash_
    //
    {
      ::std::string const& v =
        o.password_hash_;

      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.password_hash_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.password_hash_value,
        size,
        is_null,
        v);
      i.password_hash_null = is_null;
      i.password_hash_size = size;
      grew = grew || (cap != i.password_hash_value.capacity ());
    }

    // is_active_
    //
    {
      bool const& v =
        o.is_active_;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.is_active_value, is_null, v);
      i.is_active_null = is_null;
    }

    // password_change_required_
    //
    {
      bool const& v =
        o.password_change_required_;

      bool is_null (false);
      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_image (
        i.password_change_required_value, is_null, v);
      i.password_change_required_null = is_null;
    }

    // created_at_
    //
    {
      ::std::string const& v =
        o.created_at_;

      bool is_null (false);
      pgsql::value_traits<
          ::std::string,
          pgsql::id_timestamp >::set_image (
        i.created_at_value, is_null, v);
      i.created_at_null = is_null;
    }

    // updated_at_
    //
    {
      ::std::string const& v =
        o.updated_at_;

      bool is_null (false);
      pgsql::value_traits<
          ::std::string,
          pgsql::id_timestamp >::set_image (
        i.updated_at_value, is_null, v);
      i.updated_at_null = is_null;
    }

    // last_login_at_
    //
    {
      ::odb::nullable< ::std::basic_string< char > > const& v =
        o.last_login_at_;

      bool is_null (true);
      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_timestamp >::set_image (
        i.last_login_at_value, is_null, v);
      i.last_login_at_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::models::User, id_pgsql >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // id_
    //
    {
      ::std::string& v =
        o.id_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.id_value,
        i.id_size,
        i.id_null);
    }

    // first_name_
    //
    {
      ::std::string& v =
        o.first_name_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.first_name_value,
        i.first_name_size,
        i.first_name_null);
    }

    // last_name_
    //
    {
      ::std::string& v =
        o.last_name_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.last_name_value,
        i.last_name_size,
        i.last_name_null);
    }

    // patronymic_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.patronymic_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_value (
        v,
        i.patronymic_value,
        i.patronymic_size,
        i.patronymic_null);
    }

    // email_
    //
    {
      ::std::string& v =
        o.email_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.email_value,
        i.email_size,
        i.email_null);
    }

    // phone_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.phone_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_string >::set_value (
        v,
        i.phone_value,
        i.phone_size,
        i.phone_null);
    }

    // password_hash_
    //
    {
      ::std::string& v =
        o.password_hash_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_value (
        v,
        i.password_hash_value,
        i.password_hash_size,
        i.password_hash_null);
    }

    // is_active_
    //
    {
      bool& v =
        o.is_active_;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.is_active_value,
        i.is_active_null);
    }

    // password_change_required_
    //
    {
      bool& v =
        o.password_change_required_;

      pgsql::value_traits<
          bool,
          pgsql::id_boolean >::set_value (
        v,
        i.password_change_required_value,
        i.password_change_required_null);
    }

    // created_at_
    //
    {
      ::std::string& v =
        o.created_at_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_timestamp >::set_value (
        v,
        i.created_at_value,
        i.created_at_null);
    }

    // updated_at_
    //
    {
      ::std::string& v =
        o.updated_at_;

      pgsql::value_traits<
          ::std::string,
          pgsql::id_timestamp >::set_value (
        v,
        i.updated_at_value,
        i.updated_at_null);
    }

    // last_login_at_
    //
    {
      ::odb::nullable< ::std::basic_string< char > >& v =
        o.last_login_at_;

      pgsql::value_traits<
          ::odb::nullable< ::std::basic_string< char > >,
          pgsql::id_timestamp >::set_value (
        v,
        i.last_login_at_value,
        i.last_login_at_null);
    }
  }

  void access::object_traits_impl< ::models::User, id_pgsql >::
  init (id_image_type& i, const id_type& id)
  {
    bool grew (false);
    {
      bool is_null (false);
      std::size_t size (0);
      std::size_t cap (i.id_value.capacity ());
      pgsql::value_traits<
          ::std::string,
          pgsql::id_string >::set_image (
        i.id_value,
        size,
        is_null,
        id);
      i.id_null = is_null;
      i.id_size = size;
      grew = grew || (cap != i.id_value.capacity ());
    }

    if (grew)
      i.version++;
  }

  const char access::object_traits_impl< ::models::User, id_pgsql >::persist_statement[] =
  "INSERT INTO \"app_user\" "
  "(\"id\", "
  "\"first_name\", "
  "\"last_name\", "
  "\"patronymic\", "
  "\"email\", "
  "\"phone\", "
  "\"password_hash\", "
  "\"is_active\", "
  "\"password_change_required\", "
  "\"created_at\", "
  "\"updated_at\", "
  "\"last_login_at\") "
  "VALUES "
  "($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)";

  const char access::object_traits_impl< ::models::User, id_pgsql >::find_statement[] =
  "SELECT "
  "\"app_user\".\"id\", "
  "\"app_user\".\"first_name\", "
  "\"app_user\".\"last_name\", "
  "\"app_user\".\"patronymic\", "
  "\"app_user\".\"email\", "
  "\"app_user\".\"phone\", "
  "\"app_user\".\"password_hash\", "
  "\"app_user\".\"is_active\", "
  "\"app_user\".\"password_change_required\", "
  "\"app_user\".\"created_at\", "
  "\"app_user\".\"updated_at\", "
  "\"app_user\".\"last_login_at\" "
  "FROM \"app_user\" "
  "WHERE \"app_user\".\"id\"=$1";

  const char access::object_traits_impl< ::models::User, id_pgsql >::update_statement[] =
  "UPDATE \"app_user\" "
  "SET "
  "\"first_name\"=$1, "
  "\"last_name\"=$2, "
  "\"patronymic\"=$3, "
  "\"email\"=$4, "
  "\"phone\"=$5, "
  "\"password_hash\"=$6, "
  "\"is_active\"=$7, "
  "\"password_change_required\"=$8, "
  "\"created_at\"=$9, "
  "\"updated_at\"=$10, "
  "\"last_login_at\"=$11 "
  "WHERE \"id\"=$12";

  const char access::object_traits_impl< ::models::User, id_pgsql >::erase_statement[] =
  "DELETE FROM \"app_user\" "
  "WHERE \"id\"=$1";

  const char access::object_traits_impl< ::models::User, id_pgsql >::query_statement[] =
  "SELECT "
  "\"app_user\".\"id\", "
  "\"app_user\".\"first_name\", "
  "\"app_user\".\"last_name\", "
  "\"app_user\".\"patronymic\", "
  "\"app_user\".\"email\", "
  "\"app_user\".\"phone\", "
  "\"app_user\".\"password_hash\", "
  "\"app_user\".\"is_active\", "
  "\"app_user\".\"password_change_required\", "
  "\"app_user\".\"created_at\", "
  "\"app_user\".\"updated_at\", "
  "\"app_user\".\"last_login_at\" "
  "FROM \"app_user\"";

  const char access::object_traits_impl< ::models::User, id_pgsql >::erase_query_statement[] =
  "DELETE FROM \"app_user\"";

  const char access::object_traits_impl< ::models::User, id_pgsql >::table_name[] =
  "\"app_user\"";

  void access::object_traits_impl< ::models::User, id_pgsql >::
  persist (database& db, const object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::models::User, id_pgsql >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace pgsql;
    using pgsql::update_statement;

    callback (db, obj, callback_event::pre_update);

    pgsql::transaction& tr (pgsql::transaction::current ());
    pgsql::connection& conn (tr.connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& idi (sts.id_image ());
    init (idi, id (obj));

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::models::User, id_pgsql >::
  erase (database& db, const id_type& id)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::models::User, id_pgsql >::pointer_type
  access::object_traits_impl< ::models::User, id_pgsql >::
  find (database& db, const id_type& id)
  {
    using namespace pgsql;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::models::User, id_pgsql >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::models::User, id_pgsql >::
  reload (database& db, object_type& obj)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);
    assert (l.locked ()) /* Must be a top-level call. */;

    const id_type& id (object_traits_impl::id (obj));
    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::models::User, id_pgsql >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace pgsql;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::models::User, id_pgsql >::object_type >
  access::object_traits_impl< ::models::User, id_pgsql >::
  query (database& db, const query_base_type& q)
  {
    using namespace pgsql;
    using odb::details::shared;
    using odb::details::shared_ptr;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += " ";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        sts.connection (),
        query_statement_name,
        text,
        false,
        true,
        q.parameter_types (),
        q.parameter_count (),
        q.parameters_binding (),
        imb));

    st->execute ();
    st->deallocate ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) pgsql::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::models::User, id_pgsql >::
  erase_query (database& db, const query_base_type& q)
  {
    using namespace pgsql;

    pgsql::connection& conn (
      pgsql::transaction::current ().connection (db));

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      erase_query_statement_name,
      text,
      q.parameter_types (),
      q.parameter_count (),
      q.parameters_binding ());

    return st.execute ();
  }
}

#include <odb/post.hxx>
